version: '3.8'

services:
  admin:
    build:
      context: ./apps/admin
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://user:password@database:5432/weddnidb
      - AUTH_SECRET=supersecret

  client:
    build:
      context: ./apps/client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://user:password@database:5432/weddnidb
      - AUTH_SECRET=supersecret

  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weddnidb
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
