import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import { LogIn } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header className="bg-white/90 shadow-sm sticky top-0 z-50">
      <nav className="max-w-6xl mx-auto flex items-center justify-between px-6 py-4">
        {/* Logo */}
        <div className="flex items-center gap-2">
          <img src="/logoo.png" alt="Monasabet Logo" className="h-16 w-auto" />
        
        </div>
        {/* Navigation */}
        <ul className="flex gap-8 text-base font-semibold text-[#3A3A3A] mb-2 md:mb-0">
          <li><a href="/" className="hover:text-[#1CCFC9] transition">Accueil</a></li>
          <li><a href="/evenement" className="hover:text-[#1CCFC9] transition">Événements</a></li>
          <li><a href="#" className="hover:text-[#1CCFC9] transition">Lieux</a></li>
          <li><a href="#" className="hover:text-[#1CCFC9] transition">Services</a></li>
          <li><a href="#" className="hover:text-[#1CCFC9] transition">À propos</a></li>
          <li><a href="#" className="hover:text-[#1CCFC9] transition">Contact</a></li>
        </ul>
        {/* Se connecter */}
        <a
          href="#"
          className="ml-4 flex items-center gap-2 bg-[#F45B5B] text-white px-6 py-4 rounded-full font-bold shadow hover:bg-[#d63d3d] transition"
        >
          Se connecter
        </a>
      </nav>
      {/* Mobile nav (optionnel) */}
      <div className="md:hidden flex flex-wrap justify-center gap-4 pb-2">
        <a href="#" className="text-[#3A3A3A] font-semibold hover:text-[#1CCFC9]">Accueil</a>
        <a href="#" className="text-[#3A3A3A] font-semibold hover:text-[#1CCFC9]">Événements</a>
        <a href="#" className="text-[#3A3A3A] font-semibold hover:text-[#1CCFC9]">Lieux</a>
        <a href="#" className="text-[#3A3A3A] font-semibold hover:text-[#1CCFC9]">Services</a>
        <a href="#" className="text-[#3A3A3A] font-semibold hover:text-[#1CCFC9]">À propos</a>
        <a href="#" className="text-[#3A3A3A] font-semibold hover:text-[#1CCFC9]">Contact</a>
        <a href="#" className="bg-[#F45B5B] text-white px-4 py-2 rounded-full font-bold shadow hover:bg-[#d63d3d] transition">Se connecter</a>
      </div>
    </header>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
